/**
 * rulHardcoded.js
 * AUTO-GENERATED by scripts/train-rul.js (emitRulModelModule) — do not edit by hand.
 * The mission-loop-trained RUL ridge regressor frozen as source literals so the
 * fitted model is available at runtime with zero retraining and zero file I/O:
 * regenerate with "node scripts/train-rul.js" to keep it in sync.
 */

'use strict';

const HARDCODED_MODEL = Object.freeze({
  "type": "ridge-rul-regressor",
  "version": 1,
  "featureOrder": [
    "currentHealth",
    "healthSlope",
    "healthStd",
    "healthMean",
    "anomalyMean",
    "anomalySlope"
  ],
  "means": [
    27.59016393442622,
    -0.3720345009938184,
    6.311888212412926,
    45.19016393442621,
    2.038857026082504,
    0.009409546545728545
  ],
  "stds": [
    16.243411828860896,
    0.29033057284552427,
    4.661858742925793,
    15.330983835512537,
    0.21525047998570637,
    0.020651992270772537
  ],
  "weights": [
    0.11074844833760344,
    0.0669933004328716,
    0.009680602332151941,
    -0.01802025676214753,
    0.04391791623601514,
    0.06740606882211997
  ],
  "intercept": 0.09249733463709546,
  "residualStd": 0.12083657735542222,
  "n": 61,
  "generatedBy": "scripts/train-rul.js",
  "params": {
    "seedBase": 7,
    "runs": 90,
    "healthFloor": 25,
    "ticksPerRun": 900
  },
  "source": "hardcoded-mission-loop"
});

module.exports = { HARDCODED_MODEL };
