/**
 * rulRegressor.js
 * -----------------------------------------------------------------------
 * Ridge-linear RUL regressor, *fitted* on labeled data instead of the
 * hard-coded heuristic in rulModel.js. Features are the same engineered
 * bag deriveRulFeatures() produces (health + anomaly trend statistics);
 * labels are hours-to-threshold produced by scripts/train-rul.js from
 * PhysicsEngine degradation runs.
 *
 * The model is a plain ridge least-squares fit (no linear-algebra library):
 *   w = (XᵀX + λI)⁻¹ Xᵀy   on standardized features
 * This is deliberately interpretable — each weight tells you how much a
 * unit (std) shift in a feature shortens/lengthens life, which is the same
 * signal the SHAP pass surfaces for individual engines.
 *
 * Runtime stays on the rulModel.js heuristic unless loadRulModel() finds a
 * trained model file (analytics/models/rul-regressor.json, committed with
 * the repo via scripts/train-rul.js) — fully additive, zero behaviour change
 * for existing callers.
 * -----------------------------------------------------------------------
 */

'use strict';

const fs = require('fs');
const path = require('path');

const { invertMatrix } = require('./mathUtils');
const { clamp, mean } = require('./mathUtils');
const { MAX_RUL_HOURS } = require('./rulModel');

const DEFAULT_FEATURE_ORDER = ['currentHealth', 'healthSlope', 'healthStd', 'healthMean', 'anomalyMean', 'anomalySlope'];
const RUL_MODEL_PATH = path.join(__dirname, 'models', 'rul-regressor.json');
const RUL_HARDCODED_PATH = path.join(__dirname, 'rulHardcoded.js');

// The mission-loop-trained model, frozen as source literals (generated by
// scripts/train-rul.js -> emitRulModelModule). Loaded once at require time so
// predictions never depend on file I/O or a retraining step at runtime.
let RUL_HARDCODED_MODEL = null;
try {
  RUL_HARDCODED_MODEL = deepFreeze(require('./rulHardcoded').HARDCODED_MODEL);
} catch (_err) {
  RUL_HARDCODED_MODEL = null;
}

function deepFreeze(value) {
  if (value && typeof value === 'object') {
    for (const key of Object.keys(value)) deepFreeze(value[key]);
    Object.freeze(value);
  }
  return value;
}

/** Builds the feature vector consumed by train/predict, in model order. */
function buildFeatureVector(features, featureOrder) {
  return featureOrder.map((k) => {
    const v = features ? features[k] : undefined;
    return typeof v === 'number' && Number.isFinite(v) ? v : 0;
  });
}

/**
 * @param {Array<{ features: Object, hours: number }>} dataset - labeled samples
 * @param {Object} [opts] @param {number} [opts.ridge] @param {featureOrder}
 * @returns {Object} fitted model (plain object; JSON-serializable)
 */
function trainRulModel(dataset, opts = {}) {
  if (!Array.isArray(dataset) || dataset.length < 5) {
    throw new Error('trainRulModel requires at least 5 labeled samples');
  }
  const featureOrder = Array.isArray(opts.featureOrder) && opts.featureOrder.length
    ? opts.featureOrder : DEFAULT_FEATURE_ORDER;
  const ridge = Number.isFinite(opts.ridge) && opts.ridge >= 0 ? opts.ridge : 1.0;

  const rows = dataset
    .filter((d) => d && d.features && typeof d.hours === 'number' && Number.isFinite(d.hours))
    .map((d) => ({ x: buildFeatureVector(d.features, featureOrder), y: Math.max(0, d.hours) }));
  if (rows.length < 5) throw new Error('trainRulModel requires at least 5 samples with finite features and hours');

  // Standardization params from the training data.
  const d = featureOrder.length;
  const means = new Array(d).fill(0);
  const stds = new Array(d).fill(0);
  for (const r of rows) for (let i = 0; i < d; i++) means[i] += r.x[i] / rows.length;
  for (const r of rows) for (let i = 0; i < d; i++) stds[i] += (r.x[i] - means[i]) ** 2 / rows.length;
  for (let i = 0; i < d; i++) stds[i] = Math.sqrt(stds[i]) < 1e-9 ? 1 : Math.sqrt(stds[i]);

  const standardize = (x) => x.map((v, i) => (v - means[i]) / stds[i]);
  const yMean = mean(rows.map((r) => r.y));

  // Normal equations with ridge:  (XᵀX + λI) w = Xᵀ(y - ȳ)
  const XtX = Array.from({ length: d }, () => new Array(d).fill(0));
  const Xty = new Array(d).fill(0);
  for (const r of rows) {
    const z = standardize(r.x);
    const yc = r.y - yMean;
    for (let i = 0; i < d; i++) {
      Xty[i] += z[i] * yc;
      for (let j = 0; j < d; j++) XtX[i][j] += z[i] * z[j];
    }
  }
  for (let i = 0; i < d; i++) XtX[i][i] += ridge;
  const weights = rows.length ? matVec(invertMatrix(XtX, ridge), Xty) : new Array(d).fill(0);

  // Residual std on the training set (for the confidence band).
  let sse = 0;
  for (const r of rows) {
    const z = standardize(r.x);
    const pred = yMean + z.reduce((a, w, i) => a + w * weights[i], 0);
    sse += (r.y - pred) ** 2;
  }
  const residualStd = rows.length > 2 ? Math.sqrt(sse / (rows.length - d - 1) || 0) : 0;

  return {
    type: 'ridge-rul-regressor',
    version: 1,
    featureOrder,
    means,
    stds,
    weights,
    intercept: yMean,
    residualStd,
    n: rows.length,
  };
}

/**
 * @param {Object} model1 - fitted model (plain object)
 * @param {Object} features - feature bag (deriveRulFeatures shape)
 * @returns {{ rul: number, confidenceLow: number, confidenceHigh: number, contribs: Object }}
 */
function predictRul(model, features) {
  if (!model || !Array.isArray(model.featureOrder) || !Array.isArray(model.weights)) {
    throw new TypeError('predictRul requires a fitted model (see trainRulModel)');
  }
  const x = buildFeatureVector(features, model.featureOrder);
  const z = x.map((v, i) => {
    const sd = model.stds && model.stds[i] ? model.stds[i] : 1;
    return (v - (model.means ? model.means[i] : 0)) / sd;
  });
  const base = Number.isFinite(model.intercept) ? model.intercept : 0;
  const rul = clamp(base + z.reduce((a, v, i) => a + v * (model.weights[i] || 0), 0), 0, MAX_RUL_HOURS);

  const residualStd = Number.isFinite(model.residualStd) ? model.residualStd : MAX_RUL_HOURS * 0.15;
  const uncertainty = clamp(residualStd * 1.5, MAX_RUL_HOURS * 0.03, MAX_RUL_HOURS * 0.5);

  const contribs = {};
  z.forEach((v, i) => { contribs[model.featureOrder[i]] = v * (model.weights[i] || 0); });

  return {
    rul: Math.round(rul),
    confidenceLow: Math.round(clamp(rul - uncertainty, 0, rul)),
    confidenceHigh: Math.round(clamp(rul + uncertainty, rul, MAX_RUL_HOURS)),
    contribs,
  };
}

function saveRulModel(model, file = RUL_MODEL_PATH) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, JSON.stringify(model, null, 2) + '\n', 'utf8');
  return file;
}

/**
 * Emit the fitted model as a self-contained JS module (rulHardcoded.js) so the
 * mission-loop-trained model is baked into the source tree — deterministic,
 * no file I/O at inference time. Regenerated by scripts/train-rul.js whenever
 * the model is retrained.
 * @param {Object} model - fitted model (trainRulModel output)
 * @param {string} [file] - output path (default RUL_HARDCODED_PATH)
 * @returns {string} the file written
 */
function emitRulModelModule(model, file = RUL_HARDCODED_PATH) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  const fields = {};
  for (const key of ['type', 'version', 'featureOrder', 'means', 'stds', 'weights', 'intercept', 'residualStd', 'n', 'generatedBy', 'params']) {
    if (model && model[key] !== undefined) fields[key] = model[key];
  }
  fields.source = 'hardcoded-mission-loop';
  const src = [
    '/**',
    ' * rulHardcoded.js',
    ' * AUTO-GENERATED by scripts/train-rul.js (emitRulModelModule) — do not edit by hand.',
    ' * The mission-loop-trained RUL ridge regressor frozen as source literals so the',
    ' * fitted model is available at runtime with zero retraining and zero file I/O:',
    ' * regenerate with "node scripts/train-rul.js" to keep it in sync.',
    ' */',
    '',
    "'use strict';",
    '',
    'const HARDCODED_MODEL = Object.freeze(' + JSON.stringify(fields, null, 2) + ');',
    '',
    'module.exports = { HARDCODED_MODEL };',
    '',
  ].join('\n');
  fs.writeFileSync(file, src, 'utf8');
  return file;
}

/** @returns {Object|null} committed model, or a null-safe fallback. */
function loadRulModel(file) {
  const explicit = arguments.length > 0;
  const target = explicit ? file : RUL_MODEL_PATH;
  try {
    const parsed = JSON.parse(fs.readFileSync(target, 'utf8'));
    if (parsed && parsed.type === 'ridge-rul-regressor' && Array.isArray(parsed.weights)) {
      return { ...parsed, loadedFrom: target };
    }
  } catch (_err) {
    // fall through
  }
  // Only the DEFAULT artifact path falls back to the embedded model; an
  // explicitly requested missing/invalid file still resolves to null.
  if (!explicit && RUL_HARDCODED_MODEL) return { ...RUL_HARDCODED_MODEL, loadedFrom: 'embedded' };
  return null;
}

function matVec(matrix, vec) {
  return matrix.map((row) => row.reduce((a, v, j) => a + v * vec[j], 0));
}

module.exports = {
  trainRulModel,
  predictRul,
  saveRulModel,
  emitRulModelModule,
  loadRulModel,
  buildFeatureVector,
  DEFAULT_FEATURE_ORDER,
  RUL_MODEL_PATH,
  RUL_HARDCODED_PATH,
  HARDCODED_MODEL: RUL_HARDCODED_MODEL,
};