/**
 * twin_core/liveHistoryStore.js
 * -----------------------------------------------------------------------
 * Bounded rolling live-telemetry history, one file per fleet engine — the
 * complement to store.js (which records whole *missions*). While a mission
 * recording is an append-only dataset generated by replay/missionRunner,
 * the live fleet is an endless stream: history must be a rolling window
 * with a hard line cap so disk use stays flat over days of uptime.
 *
 * Layout: <data dir>/live/<engineId>.jsonl   ({ t: <ms epoch>, ...reading })
 *
 * Configuration (environment, read lazily on every call):
 *   TWIN_DATA_DIR                   data directory (default: twin_core/data)
 *   TWIN_LIVE_HISTORY_MAX_LINES     lines kept per engine (default 5000;
 *                                   oldest dropped first; file rewritten with
 *                                   just the tail when the cap would be hit)
 *
 * The in-memory ring is the source of truth for read() (so appends are
 * visible immediately, like store.js's read-your-writes); the JSONL file is
 * a crash-recovery log that is re-hydrated into the ring on first touch of
 * an engine. engineId validation is delegated to twin_core/store.assertId.
 * -----------------------------------------------------------------------
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { assertId } = require('./store');

const DEFAULT_MAX_LINES = 5000;
const FLUSH_INTERVAL_MS = 2000; // debounce between a burst of appends and a disk write
const MAX_BUFFERED_LINES = 2000; // force a flush when the pending batch gets this big
const IDLE_STATE_TTL_MS = 5 * 60 * 1000;
const states = new Map(); // engineId -> { engineId, lines[], persistedCount, loaded, timer, lastAppend }

function dataDir() {
  return path.resolve(process.env.TWIN_DATA_DIR || path.join(__dirname, 'data'));
}

function positiveIntEnv(name, dflt) {
  const n = Number.parseInt(process.env[name], 10);
  return Number.isFinite(n) && n > 0 ? n : dflt;
}

function liveFile(engineId) {
  assertId('engineId', engineId);
  return path.join(dataDir(), 'live', `${engineId}.jsonl`);
}

function parseLine(line) {
  try {
    const obj = JSON.parse(line);
    return obj !== null && typeof obj === 'object' && !Array.isArray(obj) ? obj : null;
  } catch (_err) {
    return null; // corrupt / partially-written line (crash mid-flush): skip
  }
}

function isInside(root, target) {
  const rel = path.relative(root, target);
  return rel !== '' && !rel.startsWith('..') && !path.isAbsolute(rel);
}

function resolveLiveDir() {
  const root = dataDir();
  const dir = path.join(root, 'live');
  if (!isInside(root, dir)) throw new RangeError('live history directory escapes the data directory');
  return dir;
}

// Re-hydrate the ring from whatever is on disk (crash recovery). Wrapped in
// try/catch: an unreadable file must degrade to an empty history, not crash
// the telemetry tick.
function load(state) {
  const file = liveFile(state.engineId);
  let raw = '';
  try { raw = fs.readFileSync(file, 'utf8'); } catch (_err) { /* empty history */ }
  // A truncated tail (crash mid-flush) may leave the file without a trailing
  // newline — appended lines would otherwise merge into the broken last line.
  state.fileEndedNewline = raw.length === 0 || raw.endsWith('\n');
  const parsed = [];
  for (const line of raw.split('\n')) {
    const obj = parseLine(line);
    if (obj) { parsed.push(obj); if (parsed.length > state.maxLines) parsed.shift(); }
  }
  state.lines = parsed;
  state.persistedCount = parsed.length;
  state.staleCount = 0;
  state.loaded = true;
}

function getState(engineId) {
  assertId('engineId', engineId);
  let st = states.get(engineId);
  if (!st) {
    st = {
      engineId,
      lines: [],
      persistedCount: 0,
      staleCount: 0,
      loaded: false,
      fileEndedNewline: true,
      timer: null,
      lastAppend: Date.now(),
      // process.env reads are slow on Windows: resolve the cap once per engine
      maxLines: positiveIntEnv('TWIN_LIVE_HISTORY_MAX_LINES', DEFAULT_MAX_LINES),
    };
    states.set(engineId, st);
  }
  if (!st.loaded) load(st);
  return st;
}

function sweepIdleStates() {
  const cutoff = Date.now() - IDLE_STATE_TTL_MS;
  for (const [key, st] of states) {
    if (!(st.persistedCount < st.lines.length) && !st.timer && st.lastAppend < cutoff) states.delete(key);
  }
}

function flushState(st) {
  if (st.timer) { clearTimeout(st.timer); st.timer = null; }
  const pending = st.lines.length - st.persistedCount; // lines not yet on disk
  if (!pending) return;
  const file = liveFile(st.engineId);
  try {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    // Lines physically on disk may exceed what is still in the ring: `staleCount`
    // tracks persisted lines that were rolled out of the ring's front. Once disk
    // (+ this pending batch) would exceed the cap, rewrite the file as exactly
    // the bounded tail instead of appending indefinitely.
    const onDisk = st.persistedCount + st.staleCount;
    if (onDisk + pending > st.maxLines) {
      const payload = `${st.lines.map((r) => JSON.stringify(r)).join('\n')}\n`;
      fs.writeFileSync(file, payload, 'utf8');
      st.staleCount = 0;
      st.fileEndedNewline = true;
    } else {
      const toWrite = st.lines.slice(st.persistedCount);
      const payload = `${toWrite.map((r) => JSON.stringify(r)).join('\n')}\n`;
      // Ensure the previous line is terminated before appending (crash safety).
      if (!st.fileEndedNewline) fs.appendFileSync(file, '\n', 'utf8');
      fs.appendFileSync(file, payload, 'utf8');
      st.fileEndedNewline = true;
    }
    st.persistedCount = st.lines.length;
  } catch (err) {
    console.error(`[twin_core/liveHistoryStore] flush failed for ${st.engineId}:`, err.message);
  }
}

function scheduleFlush(st) {
  if (st.timer) return;
  st.timer = setTimeout(() => {
    st.timer = null;
    flushState(st);
    sweepIdleStates();
  }, FLUSH_INTERVAL_MS);
  // don't hold the process open just for a pending flush
  if (st.timer.unref) st.timer.unref();
}

/** Buffers one reading into a fleet engine's rolling history. Always true: the window rolls. */
function append(engineId, reading) {
  assertId('engineId', engineId);
  if (reading === null || typeof reading !== 'object' || Array.isArray(reading)) {
    throw new TypeError('reading must be a plain object');
  }
  const st = getState(engineId);
  st.lines.push({ t: Date.now(), ...reading });
  if (st.lines.length > st.maxLines) {
    st.lines.shift();
    // A persisted line rolled off the ring's front: the file still holds it,
    // so count it as "stale on disk" (flushState uses this for the cap math).
    if (st.persistedCount > 0) { st.persistedCount--; st.staleCount++; }
  }
  st.lastAppend = Date.now();
  // large batch: flush now instead of waiting out the debounce
  if (st.lines.length - st.persistedCount >= MAX_BUFFERED_LINES) flushState(st);
  else scheduleFlush(st);
  return true;
}

/** Forces buffered lines for one engine to disk. Best-effort, never throws. */
function flush(engineId) {
  assertId('engineId', engineId);
  const st = states.get(engineId);
  if (st) flushState(st);
}

/** Flushes every pending buffer (call on graceful shutdown). */
function flushAll() {
  for (const st of states.values()) flushState(st);
  states.clear();
}

/**
 * Rolling history for one engine, oldest first. Values are the in-memory
 * ring, so flushes are never required to read current data.
 */
function read(engineId) {
  const st = getState(engineId);
  return st.lines.slice();
}

/** Clears an engine's history from memory and disk. */
function clear(engineId) {
  assertId('engineId', engineId);
  const st = states.get(engineId);
  if (st) { if (st.timer) clearTimeout(st.timer); states.delete(engineId); }
  try { fs.rmSync(liveFile(engineId), { force: true }); return true; } catch (_err) { return false; }
}

/** Bookkeeping for tests / the dashboard footer. */
function stats(engineId) {
  const st = getState(engineId);
  return {
    engineId,
    count: st.lines.length,
    buffered: st.lines.length - st.persistedCount,
    persistedCount: st.persistedCount,
    maxLines: st.maxLines,
    lastAppend: st.lastAppend,
    file: liveFile(engineId),
  };
}

module.exports = {
  append,
  read,
  flush,
  flushAll,
  clear,
  stats,
  liveFile,
  get LIVE_DIR() { return resolveLiveDir(); },
};